version: '3.8'

services:
  spark-master:
    image: bitnami/spark:3.4.1
    container_name: animeverse-spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "8081:8080"
      - "7077:7077"
    volumes:
      - ./spark_apps:/opt/bitnami/spark/work-dir
      - ./jars:/opt/bitnami/spark/jars
    networks:
      - animeverse_network

  spark-worker-1:
    image: bitnami/spark:3.4.1
    container_name: animeverse-spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./spark_apps:/opt/bitnami/spark/work-dir
      - ./jars:/opt/bitnami/spark/jars
    networks:
      - animeverse_network
    depends_on:
      - spark-master

  spark-worker-2:
    image: bitnami/spark:3.4.1
    container_name: animeverse-spark-worker-2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./spark_apps:/opt/bitnami/spark/work-dir
      - ./jars:/opt/bitnami/spark/jars
    networks:
      - animeverse_network
    depends_on:
      - spark-master

networks:
  animeverse_network:
    external: true