version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: animeverse-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-admin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-password123}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - animeverse_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio-init:
    image: minio/mc:latest
    container_name: animeverse-minio-init
    depends_on:
      - minio
    networks:
      - animeverse_network
    entrypoint: >
      /bin/sh -c "
      sleep 10 &&
      mc alias set myminio http://minio:9000 admin password123 &&
      mc mb myminio/bronze-layer --ignore-existing &&
      mc mb myminio/silver-layer --ignore-existing &&
      mc mb myminio/gold-layer --ignore-existing &&
      mc mb myminio/warehouse --ignore-existing &&
      echo 'MinIO buckets created successfully!'
      "

volumes:
  minio_data:

networks:
  animeverse_network:
    external: true