# Apache Spark Processing - WORKING VERSION
  spark-master:
    image: apache/spark:3.4.1-scala2.12-java11-python3-ubuntu
    container_name: animeverse-spark-master
    environment:
      - SPARK_MASTER_HOST=0.0.0.0
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
    ports:
      - "8081:8080"
      - "7077:7077"
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    volumes:
      - ./processing/spark_apps:/opt/spark/work-dir
    networks:
      - animeverse_network

  spark-worker-1:
    image: apache/spark:3.4.1-scala2.12-java11-python3-ubuntu
    container_name: animeverse-spark-worker-1
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    volumes:
      - ./processing/spark_apps:/opt/spark/work-dir
    networks:
      - animeverse_network
    depends_on:
      - spark-master